MAX_PROJECT_SYSTEM_PROMPT_LENGTH = 8000
MIN_PROJECT_RETRIEVAL_TOP_K = 1
MAX_PROJECT_RETRIEVAL_TOP_K = 40
DEFAULT_PROJECT_RETRIEVAL_TOP_K = 8
MIN_PROJECT_RETRIEVAL_MIN_SCORE = 0.0
MAX_PROJECT_RETRIEVAL_MIN_SCORE = 1.0
DEFAULT_PROJECT_RETRIEVAL_MIN_SCORE = 0.3
